---
- hosts: all
  connection: local

  vars_files:
    - default.config.yml

  vars_prompt:
    - name: user_mas_email
      prompt: "Enter Mac Store email?"
      private: no
      default: "" 
    - name: user_mas_password
      prompt: "Enter Mac Store Password?"
      private: yes
      default: ""

  pre_tasks:
    - include_vars: "{{ item }}"
      with_fileglob:
        - ../config.yml

  roles:
    - williamyeh.oracle-java
    - geerlingguy.dotfiles
    - geerlingguy.homebrew
    - name: geerlingguy.mas
      when: mas_installed_apps

  tasks:
    - include: tasks/ansible-setup.yml

    - include: tasks/sudoers.yml
      when: configure_sudoers

#    - include: tasks/terminal.yml
#      when: configure_terminal

    - include: tasks/macos.yml
      when: configure_macos
